[#1006] Set domain for authorization cookie
cyfronet-fid/sat4envi pull request #1008
Opened 2020-12-09 11:24 UTC by jswk

Depending on the property jwt.cookie.domain the cookie's domain is
either fetched from header Host (in case the property is null or blank)
and set to the value from the property otherwise.

Closes: #1006.

2020-12-09 12:34 UTC, kmarszalek approved these changes

2020-12-11 13:28 UTC, danielkryska approved these changes

2020-12-11 13:34 UTC, kmarszalek requested changes
dot

2020-12-11 13:36 UTC, kmarszalek approved these changes

2020-12-11 13:37 UTC, merged