Minor fixes: Typos, missing translations, invitation bugs
cyfronet-fid/sat4envi pull request #1016
Opened 2020-12-11 13:18 UTC by danielkryska

- Fix user password change [#788](https://github.com/cyfronet-fid/sat4envi/issues/788)
The city name is not highlighted during navigating with the arrows [#791](https://github.com/cyfronet-fid/sat4envi/issues/791)
- [FIX] In the generated report and inconsistent names [#815](https://github.com/cyfronet-fid/sat4envi/issues/815)
Confusing message when trying to generate a token [#819](https://github.com/cyfronet-fid/sat4envi/issues/819)
- [FIX] URL in dashboard and redirection after clicking on the button  <_Anuluj> in edit mode and in the mode of adding a new institution [#873](https://github.com/cyfronet-fid/sat4envi/issues/873)
- WAITING nad REJECTED near invited person should be written in polish.
- [Fix] sending invitation second time on the same mail [#959](https://github.com/cyfronet-fid/sat4envi/issues/959)
- [FIX] Polygon search update and disappearing polygon after logging in and possibility draw polygon on "Zdjecia satelitarne" [#963](https://github.com/cyfronet-fid/sat4envi/issues/963) (?)
- [Fix] logo size [#988](https://github.com/cyfronet-fid/sat4envi/issues/988)
- [Fix] "Wczytaj konfigurację" in modal should be replace to name "Konfiguruj WMS"
- Button<_WRÓĆ DO POPRZEDNIEJ STRONY> does not work correctly [#843](https://github.com/cyfronet-fid/sat4envi/issues/843)
- Problem with logging in after making a mistake [#841](https://github.com/cyfronet-fid/sat4envi/issues/841) (medium)
- Problem with the correct search of the town after pressing enter [#957](https://github.com/cyfronet-fid/sat4envi/issues/957)

2020-12-11 14:52 UTC, jswk requested changes
The second case from #873 is still present (i.e. the URL in dashboard contains info about map view).

The second case from #963 is still present (i.e. the search polygon disappears after login).

#957 is also still present (when I click enter before loading the results I get redirected to the previous first result).

Either remove these tickets from the commit message and PR or comment that they are not fixed entirely.

2020-12-14 07:22 UTC, danielkryska commented
> The second case from #873 is still present (i.e. the URL in dashboard contains info about map view).
ok

> The second case from #963 is still present (i.e. the search polygon disappears after login).
It's missing feature not a bug. It would be considered in other PR. (2/3 fixes requests from this ticket are fetures. In case of bug, button `Anuluj` provide from institution (add/edit) form into it's profile.

> #957 is also still present (when I click enter before loading the results I get redirected to the previous first result).
ok

> Either remove these tickets from the commit message and PR or comment that they are not fixed entirely.

2020-12-14 10:15 UTC, Marcelinna commented
[Fix] logo size #988 - problem still exist I added image 600x600, but in Institution Profile is displayed image 700x700.

2020-12-15 11:45 UTC, Marcelinna approved these changes

2020-12-15 11:49 UTC, jswk approved these changes

2020-12-15 11:59 UTC, merged