Full reset password flow in UI
cyfronet-fid/sat4envi pull request #1063
Opened 2021-01-06 08:42 UTC by danielkryska

2021-01-07 09:21 UTC, jswk requested changes
The `POST token-create` requires the email passed as a request param, and not as a request body, i.e.
```
POST /token-create?email=foo@bar.pl
```
and not
```
POST /token-create

{"email":"foo@bar.pl"}
```

2021-01-11 07:21 UTC, danielkryska commented
Still backend errors occurs

```
ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void pl.cyfronet.s4e.listener.PasswordListener.handle(pl.cyfronet.s4e.event.OnPasswordResetTokenEmailEvent) throws pl.cyfronet.s4e.ex.NotFoundException
s4e-backend_1  | java.lang.IllegalArgumentException: From address must not be null
s4e-backend_1  | 	at org.springframework.util.Assert.notNull(Assert.java:201)
s4e-backend_1  | 	at org.springframework.mail.javamail.MimeMessageHelper.setFrom(MimeMessageHelper.java:571)
s4e-backend_1  | 	at pl.cyfronet.s4e.service.MailService.sendEmail(MailService.java:58)
s4e-backend_1  | 	at pl.cyfronet.s4e.service.MailService.sendEmail(MailService.java:47)
s4e-backend_1  | 	at pl.cyfronet.s4e.listener.PasswordListener.handle(PasswordListener.java:59)
s4e-backend_1  | 	at pl.cyfronet.s4e.listener.PasswordListener$$FastClassBySpringCGLIB$$273883d3.invoke(<generated>)
s4e-backend_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
s4e-backend_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
s4e-backend_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
s4e-backend_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
s4e-backend_1  | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
s4e-backend_1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
s4e-backend_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
s4e-backend_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
s4e-backend_1  | 	at java.base/java.lang.Thread.run(Thread.java:834)

2021-01-11 10:13 UTC, jswk commented
The problem with sending mails in development has been fixed in #1072.

2021-01-11 12:13 UTC, jswk reviewed
I'd say that for a "full flow" you'd need error cases handled too.

For example, if you generate at least two tokens for an account, and enter the earlier token, then you get a generic 404 handler, which seems to be misleading.
![image](https://user-images.githubusercontent.com/583197/104178975-78068a00-540b-11eb-866a-4081f126b32b.png)

In that place you can also get 401 if the token has expired.

Moreover, there is an endpoint for token validation too (`GET /token-validate`), which returns the same codes prior to user entering a password, so you can provide user with information about token expiry or non-existence prior to her entering a password.

Nevertheless, the happy-path works. So it's acceptable for an initial iteration, just not as a full solution.

(A suggestion about copyright updates too, my IntelliJ only updates the year in files I change when I choose to "Update copyright" upon commit. The changes would be much easier to track down if you had it configured that way too. It's strange that it doesn't work this way out-of-the-box actually.)

2021-01-12 14:31 UTC, jswk approved these changes
Apart from the typo the flow now includes the error cases handling and is fine to merge.

2021-01-12 14:31 UTC, jswk commented on s4e-web/src/app/state/session/session.service.ts
> +                content: 'Token dla resetu hasła niestnieje'
Typo: niestnieje -> nie istnieje

2021-01-13 07:15 UTC, Marcelinna approved these changes

2021-01-13 07:39 UTC, merged