[#689] Enable actuator endpoints
cyfronet-fid/sat4envi pull request #690
Opened 2020-09-07 13:20 UTC by jswk

Enable info, health and prometheus endpoints without authorization as
they don't contain sensitive information.

Generate git and build info during build, for /actuator/info to present.

Implement a noop LoggingMailSender::testConnection, so that
/actuator/health endpoint reports correct status in development.

Closes: #689.

2020-09-08 06:34 UTC, kmarszalek requested changes
add some information in readme :)

2020-09-08 09:31 UTC, kmarszalek commented on README.md
> +There are several HTTP actuator endpoints exposed.
colon

2020-09-08 09:31 UTC, kmarszalek commented on README.md
> +There are several HTTP actuator endpoints exposed.
colon

2020-09-08 09:47 UTC, kmarszalek approved these changes

2020-09-09 13:45 UTC, wziajka approved these changes

2020-09-09 13:54 UTC, merged