683 fix add institution with form
cyfronet-fid/sat4envi pull request #707
Opened 2020-09-14 13:37 UTC by danielkryska

UI
- [ ] Run e2e
- [ ] [fix] add/update form
- [ ] [fix] set search value (in `/settings`) as URL instititution
- [ ] Hide from institution member actions buttons when go to institution profile
- [ ] Add return to `mój profil` on institution profile page when visiting as institution member

Backend
- [ ] [fix] Return added/updated institution with response
- [ ] [fix] Update should return actualized institution instead of parent

2020-09-16 10:38 UTC, michal-szostak requested changes
I have only one code issue which should be fixed before merge, a minor thing

2020-09-16 10:38 UTC, michal-szostak commented on s4e-web/src/app/views/settings/profile/profile.component.html
> +        <p *ngFor="let institution of (memberInstitutions$ | async).slice(0, MAX_INSTITUTIONS_TO_DISPLAY_PER_TILE)">
This is something that should not be done (calling functions on collections which are iterated in template)
this slice function will be called on every refresh cycle and whole list will be rerendered.
I would suggest adding this slice operation to the pipe of `memberInstitutions$` observable.

2020-09-16 10:38 UTC, michal-szostak commented on s4e-web/src/app/views/settings/profile/profile.component.html
> +        <p *ngFor="let institution of (administrationInstitutions$ | async).slice(0, MAX_INSTITUTIONS_TO_DISPLAY_PER_TILE)">
The same issue as with `memberInstitutions$` below

2020-09-21 16:00 UTC, kmarszalek requested changes
not sure how you resolved this issue 'Update should return actualized institution instead of parent' .
but i dont see how it was an issue in backend in the first place :)
backend looks good.
please add check in InstitutionControllerIntegrationTest that you got right slug.

2020-09-25 08:24 UTC, kmarszalek commented on s4e-backend/src/test/java/pl/cyfronet/s4e/controller/InstitutionControllerIntegrationTest.java
> +                .andExpect(
.andExpect(jsonPath("$.name",is(equalTo(request.getName()))))

2020-09-25 08:36 UTC, kmarszalek approved these changes

2020-09-25 10:33 UTC, merged