[Hotfix] Categories url builder for S3 icons
cyfronet-fid/sat4envi pull request #711
Opened 2020-09-15 13:05 UTC by danielkryska

2020-09-15 14:14 UTC, kmarszalek requested changes
add changelog
maybe this will do :) 
`return String.join("", fileStorageProperties.getBucket(), "/", fileStorageProperties.getKeyPrefixProductsCategoriesIcons(), iconName, ICON_EXTENSION_WITH_DOT );`
and also some test, like:
ProductCategoryServiceTest
`@Test public void shouldReturnRightString() { String iconName = productCategoryService.getIconPath("iconName"); assertEquals(iconName, "static/categories-test/iconName.svg"); }`

2020-09-15 14:14 UTC, kmarszalek commented on s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductCategoryService.java
> +        return fileStorageProperties.getBucket()
change delimiter and then it should be good. i wrote test and it was

2020-09-16 05:45 UTC, kmarszalek approved these changes

2020-09-16 06:24 UTC, wziajka approved these changes

2020-09-18 12:08 UTC, merged