[#706] Help request Form
cyfronet-fid/sat4envi pull request #812
Opened 2020-10-22 06:57 UTC by danielkryska

IMPORTANT!!! Expert email is not known, for now, it will have value xyz@mail.pl

Based on:
https://g3v8he.axshare.com/#g=1&p=scen1

- New functionality (modal) Wsparcie eksperckie on /map in zk options dropdown
  - Send help request to an expert email by application API
  - Send confirmation email to a user via email of the request submission
  - Show success notification on correct apply

Modal will contain
- Description where an answear will be send (on user email)
- Rodzaj wsparcia select input with options: wsparcie zdalne, wsparcie wyjazdowe
- Opis pożądanego zakresu wsparcia as tekstarea with message

Closes #706

2020-10-22 09:54 UTC, jswk requested changes
There are several things I'd see changed, otherwise seems fine.

Also, the modal doesn't disappear after sending the request. I'd expect it to disappear.

2020-10-22 09:54 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ExpertHelpController.java
> +            @ApiResponse(responseCode = "200", description = "Invitation was send"),
Correct the description

2020-10-22 09:54 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java
> +                .mvcMatchers(POST, prefix("/expert-help")).authenticated()
Access should be limited to ZK members if I understand correctly

2020-10-22 09:54 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/HelpType.java
> +     * Trough internet
Trough -> Through

2020-10-22 09:54 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/listener/ExpertHelpListener.java
> +    public final static String expertMail = "xyz@mail.pl";
I'd externalize this somewhere. Either to system property or the property DB table

2020-10-22 09:54 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/listener/ExpertHelpListener.java
> +                "email.email.expert-help-sending-confirmation.subject.subject",
You have duplicated email and subject in the property name.
Also, the property is undefined.

2020-10-23 07:37 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ExpertHelpController.java
> +    @Operation(summary = "Send invitation email to user")
You missed this.

2020-10-23 07:40 UTC, jswk commented on s4e-web/src/app/views/map-view/zk/expert-help-modal/expert-help-modal.component.ts
> +          content: 'Prośba o wsparcie experckie została wysłana',
experckie -> eksperckie

2020-10-23 07:46 UTC, jswk requested changes
Thanks for adding correct permission requirements and other fixes. Apart from the two comments, add the sample env value to `backend-production.env.template`, as we discussed. Something along the lines: `EXPERT_HELP_MAIL=<email to expert>`.
`

2020-10-23 08:54 UTC, jswk approved these changes

2020-10-27 17:05 UTC, jswk commented
I took this over from @danielkryska, changing the expert email storage to a DB property, instead of a runtime property, as sensibly suggested by @wziajka (my bad for suggesting a property in the first place).

2020-10-27 19:59 UTC, abacz approved these changes

2020-10-28 09:09 UTC, merged