[#830] Update local-dataset-1 in minio data directory
cyfronet-fid/sat4envi pull request #831
Opened 2020-10-23 14:11 UTC by jswk

Add soil moisture and Sentinel 2 stubs.

@wziajka: please create a minio-test image with the updated local-dataset-1 bucket contents, so that no volume mounting is introduced again in the master branch.

Closes: #830.

2020-10-23 14:55 UTC, kmarszalek requested changes
i would choose data to have more than one day with more than one time.
![Zrzut ekranu 2020-10-23 o 16 49 29](https://user-images.githubusercontent.com/6060538/97019377-89e53900-1550-11eb-9b50-94c62304d072.png)

2020-10-26 08:22 UTC, jswk commented
> i would choose data to have more than one day with more than one time. other than that it works.. :)

Makes sense, I will add another day worth of data then. @wziajka wait for the update with the image update.

2020-10-26 08:49 UTC, jswk commented
@wziajka it's updated now.

2020-10-26 11:10 UTC, kmarszalek approved these changes

2020-10-26 13:33 UTC, wziajka approved these changes

2020-10-26 14:25 UTC, merged