[#786] OL Loading indicator should only be affected by last OL request
cyfronet-fid/sat4envi pull request #860
Opened 2020-11-05 14:04 UTC by danielkryska

- Change Image Wms to Tile Wms loading handling

Closes #786

2020-11-06 16:13 UTC, jswk requested changes

2020-11-06 16:13 UTC, jswk commented on s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts
> +  tilesLoaderLoader.end$.then(() => loaderService.stopBackground());
From my view, once this typo (double loader) is fixed then the PR is good to go

2020-11-07 19:29 UTC, michal-szostak commented
I have a question - does this PR solves the issue which it is connected to?
Because I indeed see change from `Image` to `Tile`, but I do not see anything which would solve the #786.
(The PR instance is down, so I couldn't check there)

2020-11-09 07:25 UTC, danielkryska commented
@michal-szostak I belive this was the issue. 

Before we were using `OL` image hooks like `imageloadend` and `imageloadstart` for `ImageWms` usage only.
```
    source.once('imageloadend', () => resolve());
    source.once('imageloadstart', () => resolve());
```

, but then @jswk changed handling to `Tiles`, so finally loading methods names should be changed also. In this case to `tileloadend` and `tileloadstart`. Loading indicator we've seen `sometimes` while choosing `product` was misleading and the bug wasn't connected with unsloved stream/promise/async.
 
```
    this.end$ = new Promise((resolve) => source.once('tileloadend', () => resolve()));
    this.start$ = new Promise((resolve) => source.once('tileloadstart', () => resolve()));

2020-11-11 08:04 UTC, danielkryska commented
@michal-szostak I've updated handling of tiles loader to switch map to new incoming promise. It's working much smoother than before.

2020-11-12 13:56 UTC, jswk approved these changes
Now it works correctly. Thanks for fixing this :)

2020-11-13 09:29 UTC, michal-szostak approved these changes

2020-11-14 11:41 UTC, merged