[#799] Add live scene loading
cyfronet-fid/sat4envi pull request #866
Opened 2020-11-09 08:45 UTC by danielkryska

- Add checkbox on `/map` page to display the latest scenes of the product (send a request for new scenes every 15 minutes)
- Reload the latest scene on the map, when new occur
- When live mode is turn on ask if user is sure while
  - changing between products
  - trying to change scene (by hour/date or on time axis)

Closes #799

2020-11-09 13:15 UTC, michal-szostak commented
With PR's concerning some UI features it's good to assign some screenshots showing how does it look.

2020-11-09 13:17 UTC, michal-szostak commented
And I have one question - isn't it better to add this flag to the Scenes store?

2020-11-10 12:41 UTC, danielkryska commented
> With PR's concerning some UI features it's good to assign some screenshots showing how does it look.

Unfortunately on my Ubuntu all print screens always are black due to some graphic card issue and there weren't enough time to fix it.

2020-11-12 06:57 UTC, kmarszalek approved these changes
it works, after slack conversation time will be configurable. it reloads after time even if there was no new scene- loads old one.

2020-11-12 07:04 UTC, michal-szostak approved these changes

2020-11-12 07:09 UTC, kmarszalek requested changes
commits

2020-11-12 08:49 UTC, kmarszalek requested changes

2020-11-12 08:49 UTC, kmarszalek commented on s4e-web/src/environments/environment.common.ts
> +  liveSceneUpdateRateInMs: 1000
change to more than 1 sek and leave some comment :)

2020-11-12 09:03 UTC, kmarszalek approved these changes

2020-11-12 09:21 UTC, merged