[#797] Add password length validation when changing it
cyfronet-fid/sat4envi pull request #886
Opened 2020-11-13 14:57 UTC by jswk

Fixes: #797.

2020-11-13 15:07 UTC, kmarszalek approved these changes

2020-11-13 15:07 UTC, kmarszalek requested changes
tests?

2020-11-13 15:15 UTC, jswk commented
> tests?

The validation is based on annotations based handled by Spring, so it's tested there.

2020-11-13 15:28 UTC, kmarszalek approved these changes

2020-11-16 11:29 UTC, Marcelinna approved these changes

2020-11-16 11:59 UTC, merged