[#836] Fix adding a user to an institution on invitation acceptance
cyfronet-fid/sat4envi pull request #888
Opened 2020-11-14 11:42 UTC by danielkryska

2020-11-14 11:46 UTC, kmarszalek commented on s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java
>      public void shouldCreateUser() throws Exception {
i would make test for regiter with and wotuhout token

2020-11-16 07:58 UTC, jswk requested changes

2020-11-16 07:58 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java
> +                eventPublisher.publishEvent(confirmInvitationEvent);
I'm not a fan of breaking the SRP in this method, however I understand the workflow. Nevertheless, add a test which verifies, that if line 78 throws NFE, then creating a new user is rolled back

2020-11-16 07:58 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/RegisterRequest.java
> +    private String token;
It's an optional part, which in other endpoints is passed as query param. I would put it in query param in this case too.

2020-11-16 07:58 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/service/InvitationService.java
> +    public void confirmInvitation(String userEmail, String token) throws NotFoundException {
Great change, it's better to fetch the AppUserDetails in controller layer and inject it into the service layer.

2020-11-16 09:23 UTC, jswk requested changes

2020-11-16 09:23 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java
> +    ) throws RecaptchaException, NotFoundException {
It won't throw NFE anymore. Remove it from the declaration.

2020-11-16 09:23 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java
> +            catch (NotFoundException e) {}
Catch Exception, and not NFE, as the called methods may throw runtime exceptions too.
I'd also log the thrown exceptions at level info.

Also, remove the newline between the closing try bracket and `catch`.

2020-11-16 09:23 UTC, jswk commented on s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java
> +        assertThat(appUserRepository.findByEmail(registerRequest.getEmail()), isEmpty());
Verify a user was created after the endpoint call.

2020-11-16 13:35 UTC, jswk requested changes

2020-11-16 13:35 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java
> +                val errorMessage = e.getMessage();
You must've not commited something when adding logging.

2020-11-16 15:14 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java
> +            } catch (Exception e) {}
And why not log, as I suggested in https://github.com/cyfronet-fid/sat4envi/pull/888#discussion_r524011741?

2020-11-16 17:07 UTC, jswk requested changes

2020-11-16 17:07 UTC, jswk commented on s4e-backend/src/main/java/pl/cyfronet/s4e/controller/AppUserController.java
> +
?

2020-11-17 09:35 UTC, kmarszalek approved these changes

2020-11-17 09:44 UTC, jswk approved these changes

2020-11-17 10:01 UTC, merged