[#922] Search sentinels by polygon drawing
cyfronet-fid/sat4envi pull request #923
Opened 2020-11-23 15:47 UTC by danielkryska

- Draw polygon (as closed form) to search sentinels
- Start drawing new one by clicking on map

Closes #922

2020-11-24 06:08 UTC, kmarszalek commented
right now on pr instance you can draw many polygons and it screwing the search.. [search:sentinel-1]
![Zrzut ekranu 2020-11-24 o 07 06 04](https://user-images.githubusercontent.com/6060538/100055186-c0e68d00-2e23-11eb-84d4-38464eefc9f1.png)

2020-11-24 06:12 UTC, kmarszalek requested changes
web tests and multiple polygons

2020-11-24 07:18 UTC, danielkryska commented
Multiple polygons don't influence searching, because the `/dhus/search` endpoint is triggered at the end of drawing actual one.

2020-11-24 07:35 UTC, kmarszalek commented
ok, so multiple just doesnt look good or clear.
but, poligon is screwing search. also, you trigger search when you close polygon, why?
search, it doesnt matter if i check sentinel-1 in search or not, if i am drawing polygon i got MSG and not Sentinel. 
only if i take step back and click search button i got sentinel scenes.

2020-11-24 08:11 UTC, danielkryska commented
From now polygons should be removed (only one will be visible at time) and footprint is sent on click `search` button.

2020-11-24 11:07 UTC, jswk submitted a review, later dismissed
The problems mentioned by @kmarszalek seem to be fixed on e1b94b9, however, there's no way I've found to unset the polygon. I'd expect a button to unset the polygon somewhere.

Also, after I search using polygon, navigate to products list and back I'd expect the polygon to have been unset (especially since it's not rendered on map anymore). Currently it is still sent with search requests.

2020-11-29 12:17 UTC, abacz approved these changes

2020-11-29 17:03 UTC, Marcelinna commented
after drawing a polygon and clicking search button, search results do not appear
![image](https://user-images.githubusercontent.com/59872096/100548492-2a73fa80-326d-11eb-8d23-9e2afd513736.png)

2020-11-30 04:56 UTC, michal-szostak requested changes

2020-11-30 04:56 UTC, michal-szostak commented on s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.ts
> +    this.service.search(this.form);
why remove subscribe?

2020-11-30 06:03 UTC, michal-szostak approved these changes

2020-11-30 06:53 UTC, merged