Manage institution licence products
cyfronet-fid/sat4envi pull request #969
Opened 2020-11-30 13:48 UTC by danielkryska

IMPORTANT!!! Due to missing mock examples of products bind with specific institutions, manual tests can't be done

2020-11-30 13:52 UTC, michal-szostak approved these changes

2020-11-30 13:52 UTC, michal-szostak commented on s4e-web/src/app/views/settings/manage-products/manage-products.component.ts
> +        take(1),
If you `take(1)` then this observable completes, `untilDestroyed(this)` is reduntant

2020-11-30 14:37 UTC, jswk requested changes
There are no requests for license-grants made when I navigate to the subpage.
There are such logs in the console when I try to navigate there though:
![image](https://user-images.githubusercontent.com/583197/100622943-c3644d80-3321-11eb-858c-3f32572f4e08.png)

2020-12-03 10:15 UTC, jswk approved these changes

2020-12-03 11:35 UTC, merged